version: '3.8'
name: 'simpl-rag'

services:
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

  # backend:
  #   build:
  #     context: ./be
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - app-network
  backend:
    build: ./be
    ports:
      - "8000:8000"
    restart: "on-failure"
    environment:
      REDIS_URL: redis://redis:6379/1
      USE_MOCK_EMBEDDINGS: "True"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  redis:
    image: "redis:7-alpine"
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery_worker:
    build: ./be
    restart: "on-failure"
    environment:
      REDIS_URL: redis://redis:6379/1
      USE_MOCK_EMBEDDINGS: "True"
    command: python -m celery -A src.celery_worker:celery_app worker --loglevel=info
    depends_on:
      - redis

networks:
  app-network:
    driver: bridge
    
volumes:
  redis-data: